version: '3.1'

networks:
  express_stack:
    driver: bridge

services:
  postgresql:
    image: postgres:latest
    container_name: postgersql_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${PGSQL_PW}
      POSTGRES_DB: "blog_express"
    ports:
      - 5432:5432
    networks:
      - express_stack

  redis_image:
    image: 'redis:latest'
    container_name: redis_db
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PW}
      - REDIS_PORT=6379
    ports:
      - '6379:6379'
    command: [ "redis-server" ]
    networks:
      - express_stack
